services:

  mariadb:
    build: ./requirements/mariadb
    image: mariadb:gyepark
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:gyepark
    env_file:
      - .env
    volumes:
      - wp:/usr/share/nginx/www/gyepark.42.fr
    networks:
      - inception
    depends_on:
      - mariadb
    restart: on-failure

  nginx:
    build: ./requirements/nginx
    image: nginx:gyepark
    env_file:
      - .env
    volumes:
      - wp:/usr/share/nginx/www/gyepark.42.fr
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: on-failure

  redis:
    build: ./requirements/bonus/redis
    image: redis:gyepark
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer:gyepark
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure

  ftp:
    build: ./requirements/bonus/ftp
    image: ftp:gyepark
    env_file:
      - .env
    volumes:
      - wp:/usr/share/nginx/www/gyepark.42.fr
    networks:
      - inception
    ports:
      - "21:21"
      - "50000-50010:50000-50010"
    restart: on-failure

  cadvisor:
    build: ./requirements/bonus/cadvisor
    image: cadvisor:gyepark
    env_file:
      - .env
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
        - inception
    restart: on-failure

volumes:

  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}/db

  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}/wp

networks:
  inception:
