services:

  mariadb:
    build: ./requirements/mariadb
    image: mariadb:gyepark
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:gyepark
    env_file:
      - .env
    volumes:
      - wp:/usr/share/nginx/www/gyepark.42.fr
    networks:
      - inception
    depends_on:
      - mariadb

  nginx:
    build: ./requirements/nginx
    image: nginx:gyepark
    env_file:
      - .env
    volumes:
      - wp:/usr/share/nginx/www/gyepark.42.fr
    networks:
      - inception
    ports:
      - 443:443
    depends_on:
      - wordpress

  redis:
    build: ./requirements/bonus/redis
    image: redis:gyepark
    env_file:
      - .env
    networks:
      - inception

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer:gyepark
    env_file:
      - .env
    networks:
      - inception

  ftp:
    build: ./requirements/bonus/ftp
    image: ftp:gyepark
    env_file:
      - .env
    volumes:
      - wp:/usr/share/nginx/www/gyepark.42.fr
    networks:
      - inception
    ports:
      - "21:21"
      - "50000-50010:50000-50010"

volumes:

  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}/db

  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}/wp

networks:
  inception:
