services:

  mariadb:
    image: mariadb:gyepark
    build: ./requirements/mariadb
    env_file:
      - mariadb.env
    volumes:
      - database:/var/lib/mysql

  nginx:
    image: nginx:gyepark
    build: ./requirements/nginx
    env_file:
      - nginx.env
    volumes:
      - wp-files:/var/www/html
    depends_on:
      - wordpress
    ports:
      - 443:443

  wordpress:
    image: wordpress:gyepark
    build: ./requirements/wordpress
    env_file:
      - wordpress.env
    volumes:
      - wp-files:/wordpress
    
volumes:

  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/gyepark/data/database

  wp-files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/gyepark/data/wp-files
