services:

  mariadb:
    build: ./requirements/mariadb
    image: mariadb:gyepark
    env_file:
      - .env
    volumes:
      - database:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:gyepark
    env_file:
      - .env
    volumes:
      - wp-files:/wordpress

  nginx:
    build: ./requirements/nginx
    image: nginx:gyepark
    env_file:
      - .env
    volumes:
      - wp-files:/usr/share/nginx/www/gyepark.42.fr
    ports:
      - 443:443
    depends_on:
      - wordpress
    
volumes:

  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}/database

  wp-files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}/wp-files
