services:

  mariadb:
    build: ./requirements/mariadb
    image: mariadb:gyepark
    volumes:
      - database:/var/lib/mysql

  nginx:
    build: ./requirements/nginx
    image: nginx:gyepark
    volumes:
      - wp-files:/var/www/wordpress
    ports:
      - 443:443
    depends_on:
      - wordpress

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:gyepark
    volumes:
      - wp-files:/wordpress
    
volumes:

  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}/database

  wp-files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}/wp-files
